import { Jost } from "next/font/google";
import "./globals.css";
import Header from "@/components/header/HeaderWrapper";
import Footer from "@/components/footer/FooterWrapper";

const jost = Jost({
   variable: "--font-jost",
   subsets: ["latin"],
});

export const metadata = {
   title: "Elsass Compta",
   description: "Generated by create next app",
};

export default function RootLayout({ children }) {
   return (
      <html lang="en">
         <body className={`${jost.variable} min-h-screen flex flex-col`}>
            <Header />
            <main className="grow grid">{children}</main>
            <Footer />
         </body>
      </html>
   );
}
