import { Geist, Geist_Mono, Jost } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";

const geistSans = Geist({
   variable: "--font-geist-sans",
   subsets: ["latin"],
});

const jost = Jost({
   variable: "--font-jost",
   subsets: ["latin"],
});

export const metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default function RootLayout({ children }) {
   return (
      <html lang="en">
         <body className={` ${jost.variable}`}>
            <Header />
            {children}
         </body>
      </html>
   );
}
