import { Jost } from "next/font/google";
import "./globals.css";
import Header from "@/components/header/HeaderWrapper";
import Footer from "@/components/footer/FooterWrapper";

const jost = Jost({
   variable: "--font-jost",
   subsets: ["latin"],
   display: "swap",
   preload: true,
   weight: ["300", "400", "500", "600", "700"],
});

export const metadata = {
   title: "Elsass Compta",
   description: "Generated by create next app",
};

export default function RootLayout({ children }) {
   return (
      <html lang="en">
         <head>
            <link rel="manifest" href="/manifest.json" />
            <link rel="icon" href="/logo512.png" />
            <meta name="theme-color" content="#ffffff" />
         </head>
         <body className={`${jost.variable} min-h-screen flex flex-col`}>
            <Header />
            <main className="grow grid">{children}</main>
            <Footer />
         </body>
      </html>
   );
}
